apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: i221510-mern-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 6868
    targetPort: 6868
    nodePort: 30300
